# Generated by Django 5.0.7 on 2024-10-24 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CHAT',
            fields=[
                ('ID_CHAT', models.IntegerField(primary_key=True, serialize=False)),
                ('Generated_PLYST', models.CharField(max_length=700, null=True)),
                ('SUGERIDA_PLYST', models.CharField(max_length=700, null=True)),
                ('CREACION', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('access_token', models.CharField(max_length=500)),
                ('refresh_token', models.CharField(max_length=500)),
                ('expires_in', models.DateTimeField()),
                ('token_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USR', models.CharField(max_length=150)),
                ('Nombre', models.CharField(blank=True, max_length=25)),
                ('Apellido', models.CharField(blank=True, max_length=25)),
                ('Email', models.EmailField(max_length=254)),
                ('tokenSPFY', models.CharField(blank=True, max_length=700, unique=True)),
                ('SPFY_plan', models.CharField(blank=True, max_length=50)),
                ('MusicalPreference', models.CharField(blank=True, max_length=700)),
                ('Artistas_FAV', models.CharField(blank=True, max_length=700, null=True)),
                ('Hystorial', models.CharField(blank=True, max_length=700)),
                ('User_BirthDate', models.DateField()),
                ('UserCreateDate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='MESSAGE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USER_DESCRIP', models.TextField()),
                ('FECHA', models.DateField()),
                ('ID_CHAT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.chat')),
            ],
        ),
        migrations.CreateModel(
            name='PLAYLIST',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LINK_PLAYLIST', models.CharField(max_length=700, null=True)),
                ('ID_CHAT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.chat')),
            ],
        ),
    ]
