# Generated by Django 5.1.2 on 2024-11-11 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='Email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
