# Generated by Django 5.0.7 on 2024-09-09 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0002_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Gustos',
            field=models.CharField(max_length=700, null=True),
        ),
    ]
