# Generated by Django 5.1.2 on 2024-11-11 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0003_alter_usuario_usr_alter_usuario_usercreatedate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='User_BirthDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
