# Generated by Django 5.0.7 on 2024-10-15 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0004_chat_message_playlist_usuario_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playlist',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='ID_CHAT',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.chat'),
        ),
        migrations.AlterField(
            model_name='message',
            name='USER_DESCRIP',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='ID_CHAT',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.chat'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='Email',
            field=models.EmailField(max_length=254),
        ),
    ]
