# Generated by Django 5.0.7 on 2024-10-15 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0005_message_id_playlist_id_alter_message_id_chat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='Apellido',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='Artistas_FAV',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='Hystorial',
            field=models.CharField(blank=True, max_length=700),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='MusicalPreference',
            field=models.CharField(blank=True, max_length=700),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='Nombre',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='SPFY_plan',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tokenSPFY',
            field=models.CharField(blank=True, max_length=700, unique=True),
        ),
    ]
