# Generated by Django 5.1.2 on 2024-11-12 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0006_alter_usuario_usercreatedate_alter_usuario_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='ID_USER',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Api.usuario'),
        ),
        migrations.CreateModel(
            name='SpotifyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotify_id', models.CharField(max_length=255, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='spotify_profile', to='Api.usuario')),
            ],
        ),
    ]
