# Generated by Django 5.0.7 on 2024-10-15 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0006_alter_usuario_apellido_alter_usuario_artistas_fav_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='Usuario',
            new_name='USR',
        ),
    ]
