# Generated by Django 5.1.2 on 2024-11-12 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0007_message_id_user_spotifyprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='USR',
            field=models.CharField(max_length=150),
        ),
    ]
