# Generated by Django 5.0.7 on 2024-10-15 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0007_rename_usuario_usuario_usr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='USR',
            field=models.CharField(max_length=150),
        ),
    ]
