# Generated by Django 5.0.8 on 2024-11-12 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0007_message_id_user_spotifyprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='SPFY_plan',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='tokenSPFY',
        ),
    ]
