# Generated by Django 5.1.1 on 2024-11-12 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0008_alter_usuario_usr'),
        ('Api', '0009_alter_spotifyprofile_user'),
    ]

    operations = [
    ]
