# Generated by Django 5.0.8 on 2024-11-12 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0010_merge_20241112_1735'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SpotifyProfile',
        ),
    ]
